package com.brother.support.domain;

import java.util.Date;

public class OperationLogRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log_record.operation_log_record_id
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    private Integer operationLogRecordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log_record.method_name
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    private String methodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log_record.req_param
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    private String reqParam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log_record.rsp_param
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    private String rspParam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log_record.user_name
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log_record.create_staff
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    private String createStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log_record.create_date
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log_record.update_staff
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    private String updateStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log_record.update_date
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log_record.remark
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log_record.operation_log_record_id
     *
     * @return the value of operation_log_record.operation_log_record_id
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    public Integer getOperationLogRecordId() {
        return operationLogRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log_record.operation_log_record_id
     *
     * @param operationLogRecordId the value for operation_log_record.operation_log_record_id
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    public void setOperationLogRecordId(Integer operationLogRecordId) {
        this.operationLogRecordId = operationLogRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log_record.method_name
     *
     * @return the value of operation_log_record.method_name
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log_record.method_name
     *
     * @param methodName the value for operation_log_record.method_name
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName == null ? null : methodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log_record.req_param
     *
     * @return the value of operation_log_record.req_param
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    public String getReqParam() {
        return reqParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log_record.req_param
     *
     * @param reqParam the value for operation_log_record.req_param
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    public void setReqParam(String reqParam) {
        this.reqParam = reqParam == null ? null : reqParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log_record.rsp_param
     *
     * @return the value of operation_log_record.rsp_param
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    public String getRspParam() {
        return rspParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log_record.rsp_param
     *
     * @param rspParam the value for operation_log_record.rsp_param
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    public void setRspParam(String rspParam) {
        this.rspParam = rspParam == null ? null : rspParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log_record.user_name
     *
     * @return the value of operation_log_record.user_name
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log_record.user_name
     *
     * @param userName the value for operation_log_record.user_name
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log_record.create_staff
     *
     * @return the value of operation_log_record.create_staff
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    public String getCreateStaff() {
        return createStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log_record.create_staff
     *
     * @param createStaff the value for operation_log_record.create_staff
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    public void setCreateStaff(String createStaff) {
        this.createStaff = createStaff == null ? null : createStaff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log_record.create_date
     *
     * @return the value of operation_log_record.create_date
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log_record.create_date
     *
     * @param createDate the value for operation_log_record.create_date
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log_record.update_staff
     *
     * @return the value of operation_log_record.update_staff
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    public String getUpdateStaff() {
        return updateStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log_record.update_staff
     *
     * @param updateStaff the value for operation_log_record.update_staff
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    public void setUpdateStaff(String updateStaff) {
        this.updateStaff = updateStaff == null ? null : updateStaff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log_record.update_date
     *
     * @return the value of operation_log_record.update_date
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log_record.update_date
     *
     * @param updateDate the value for operation_log_record.update_date
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log_record.remark
     *
     * @return the value of operation_log_record.remark
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log_record.remark
     *
     * @param remark the value for operation_log_record.remark
     *
     * @mbg.generated Wed Jul 08 09:34:38 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}